# Generated by Django 5.2.3 on 2025-07-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0002_alter_profile_bio_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.CharField(help_text='Comma-separated tags (e.g. nature,portrait,travel)', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a square image (1:1) for best display.', null=True, upload_to='profiles/'),
        ),
    ]
